name: CDC CI/CD pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup GHDL
        uses: ghdl/setup-ghdl@v1
        with:
          version: v4.0.0
          backend: llvm
          investigate: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          pip install cocotb pytest cocotb-test

      - name: Run single bit cdc tests
        run: |
          # Configura GHDL como simulador
          export SIM=ghdl
          pytest ./single_bit/tb/test_bit_cdc.py

      - name: Run multi bits cdc tests
        run: |
          # Configura GHDL como simulador
          export SIM=ghdl
          pytest ./multi_bits/tb/test_gray_cdc.py
